version: '3.8'
services:
  airflow-postgres:
    image: postgres:latest
    container_name: airflow-postgres
    restart: always
    environment:
      - POSTGRES_USER=airflow_usr
      - POSTGRES_PASSWORD=airflow_pwd
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_airflow_db.sql

  airflow:
    image: airflow-local-executor
    container_name: airflow-local-executor
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/airflow_tutorial
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Taipei
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_usr:airflow_pwd@airflow-postgres/airflow_db
    entrypoint: /bin/bash docker_entrypoint.sh
    volumes:
      - ./:/airflow_tutorial
    ports:
      - '8080:8080'
    depends_on:
      - airflow-postgres
    links:
      - airflow-postgres

volumes:
  db:
    driver: local
